// Mock data for demo purposes
export const mockArtisans = [
  {
    id: 'ART001',
    name: 'Ramesh Kumar',
    craft: 'Pottery',
    location: { state: 'Rajasthan', district: 'Jaipur', village: 'Sanganer' },
    phone: '+91 98765 43210',
    email: 'ramesh.pottery@gmail.com',
    joinDate: '2023-06-15',
    experience: 12,
    monthlyIncome: 25000,
    qualityScore: 85,
    language: 'Hindi',
    incomeHistory: [
      { month: '2024-01', income: 5000 },
      { month: '2024-02', income: 6500 },
      { month: '2024-03', income: 8200 },
      { month: '2024-04', income: 12000 },
      { month: '2024-05', income: 18000 },
      { month: '2024-06', income: 25000 },
    ],
    trainingCompleted: 5,
    certifications: ['Basic Pottery', 'Quality Standards'],
    ngoPartner: 'Craft Development Foundation',
    productsListed: 23,
    activeOrders: 2,
  },
  {
    id: 'ART002',
    name: 'Priya Sharma',
    craft: 'Textiles',
    location: { state: 'Gujarat', district: 'Ahmedabad', village: 'Paldi' },
    phone: '+91 98765 43211',
    email: 'priya.textiles@gmail.com',
    joinDate: '2023-08-20',
    experience: 8,
    monthlyIncome: 32000,
    qualityScore: 92,
    language: 'Gujarati',
    incomeHistory: [
      { month: '2024-01', income: 12000 },
      { month: '2024-02', income: 15000 },
      { month: '2024-03', income: 20000 },
      { month: '2024-04', income: 25000 },
      { month: '2024-05', income: 28000 },
      { month: '2024-06', income: 32000 },
    ],
    trainingCompleted: 7,
    certifications: ['Advanced Weaving', 'Quality Standards', 'Export Documentation'],
    ngoPartner: 'Textile Craft Foundation',
    productsListed: 45,
    activeOrders: 5,
  },
];

export const mockNGOs = [
  {
    id: 'NGO001',
    name: 'Craft Development Foundation',
    registrationNumber: 'REG-2020-001',
    email: 'contact@craftdev.org',
    phone: '+91 98765 00001',
    location: { state: 'Rajasthan', districts: ['Jaipur', 'Udaipur', 'Jodhpur'] },
    craftsSupported: ['Pottery', 'Metal Work', 'Textiles'],
    artisansCount: 250,
    logo: '/JRF-Logo.png',
    establishedYear: 2020,
  },
  {
    id: 'NGO002',
    name: 'Textile Craft Foundation',
    registrationNumber: 'REG-2019-045',
    email: 'info@textilecraft.org',
    phone: '+91 98765 00002',
    location: { state: 'Gujarat', districts: ['Ahmedabad', 'Surat', 'Rajkot'] },
    craftsSupported: ['Textiles', 'Embroidery', 'Weaving'],
    artisansCount: 380,
    logo: '/Rangsutra_Logo final.webp',
    establishedYear: 2019,
  },
];

export const mockMarketPrices = [
  {
    craft: 'Pottery',
    product: 'Terracotta Vase (Medium)',
    region: 'Rajasthan',
    priceHistory: [
      { date: '2024-01', min: 200, avg: 350, max: 500 },
      { date: '2024-02', min: 220, avg: 370, max: 520 },
      { date: '2024-03', min: 250, avg: 400, max: 550 },
      { date: '2024-04', min: 280, avg: 430, max: 580 },
      { date: '2024-05', min: 300, avg: 450, max: 600 },
      { date: '2024-06', min: 320, avg: 480, max: 650 },
    ],
    demandTrend: 'increasing',
    seasonalPeak: ['October', 'November', 'December'],
  },
];

export const mockTrainings = [
  {
    id: 'TRN001',
    title: 'Advanced Pottery Finishing Techniques',
    craft: 'Pottery',
    level: 'Intermediate',
    duration: '3 hours',
    language: ['Hindi', 'English'],
    rating: 4.6,
    enrollments: 45,
    completionRate: 78,
  },
  {
    id: 'TRN002',
    title: 'Business Skills for Artisans',
    craft: 'All',
    level: 'Beginner',
    duration: '5 hours',
    language: ['Hindi', 'English', 'Gujarati'],
    rating: 4.8,
    enrollments: 120,
    completionRate: 85,
  },
  {
    id: 'TRN003',
    title: 'Digital Marketing Basics',
    craft: 'All',
    level: 'Beginner',
    duration: '4 hours',
    language: ['Hindi', 'English'],
    rating: 4.7,
    enrollments: 89,
    completionRate: 82,
  },
  {
    id: 'TRN004',
    title: 'Quality Standards & Certification',
    craft: 'All',
    level: 'Advanced',
    duration: '6 hours',
    language: ['Hindi', 'English', 'Tamil'],
    rating: 4.9,
    enrollments: 67,
    completionRate: 88,
  },
];

export const mockEvents = [
  {
    id: 'EVT001',
    name: 'National Handicraft Fair 2024',
    type: 'Exhibition',
    date: '2024-11-15',
    endDate: '2024-11-20',
    location: { venue: 'Pragati Maidan', city: 'New Delhi', state: 'Delhi' },
    craftsRelevant: ['Pottery', 'Textiles', 'Bamboo', 'Metal Work'],
    description: 'Annual exhibition showcasing traditional Indian handicrafts...',
    registrationFee: 5000,
    expectedAttendees: 50000,
    expectedSales: 45000,
    registrationDeadline: '2024-10-15',
    benefits: ['National exposure', 'Buyer meetings', 'Awards', 'Subsidized stalls'],
    organizer: 'Development Commissioner (Handicrafts)',
    registeredArtisans: 23,
    relevanceScore: 92,
  },
];

